INSERT INTO allbums (name, release_year)
VALUES ('Metallica', 1991),
       ('Nevermind', 1991),
       ('Follow the Leader', 1998),
       ('Creeping Death (Live)', 2019);

INSERT INTO executors (name)
VALUES ('Jaims Hatfild'),
       ('Lars Ulrisch'),
       ('Kirk Hemmet'),
       ('Jason Newsted'),
       ('Kurt Cobain'),
       ('Krist Novoselic'),
       ('David Grohl'),
       ('Jonathan Davis'),
       ('Munky'),
       ('Head'),
       ('Fieldy'),
       ('Ray Luzier');

INSERT INTO allbums_executors (allbum_id, executor_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (2, 5),
       (2, 6),
       (2, 7),
       (3, 8),
       (3, 9),
       (3, 10),
       (3, 11),
       (3, 12),
       (4, 1),
       (4, 2),
       (4, 3);

INSERT INTO tracks (name, duration, allbum_id)
VALUES ('Enter Sandman', 330, 1),
       ('Sad but True', 323, 1),
       ('The Unforgiven', 386, 1),
       ('Wherever I May Roam', 403, 1),
       ('Don t Tread on Me', 240, 1),
       ('Nothing Else Matters', 387, 1),
       ('The God That Failed', 307, 1),
       ('Smells Like Teen Spirit', 301, 2),
       ('In Bloom', 854, 2),
       ('Come as You Are', 218, 2),
       ('Breed', 183, 2),
       ('Lithium', 256, 2),
       ('Polly', 176, 2),
       ('Territorial Pissings', 142, 2),
       ('Drain You', 223, 2),
       ('Lounge Act', 156, 2),
       ('Stay Away', 212, 2),
       ('On a Plain', 196, 2),
       ('Something in the Way', 230, 2),
       ('It’s On!', 269, 3),
       ('Freak on a Leash', 255, 3),
       ('Got the Life', 225, 3),
       ('Dead Bodies Everywhere', 285, 3),
       ('Children of the Korn', 232, 3),
       ('Pretty', 252, 3),
       ('All in the Family', 289, 3),
       ('Reclaim my Place', 272, 3),
       ('Justin', 257, 3),
       ('Seed', 355, 3),
       ('For Whom The Bell Tolls (Live)', 474, 4),
       ('Fade To Black (Live)', 457, 4),
       ('Nothing Else Matters (Live)', 520, 4),
       ('Wherever I May Roam (Live)', 451, 4),
       ('So What (Live)', 201, 4),
       ('Creeping Death (Live)', 427, 4),
       ('One (Live)', 421, 4),
       ('Harvester Of Sorrow (Live)', 408, 4);

INSERT INTO genres (name)
VALUES ('Matal'),
       ('Grunge'),
       ('Punk rock'),
       ('Nu metal'),
       ('Rap metal');

INSERT INTO genres_executors (genre_id, executor_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (2, 5),
       (2, 6),
       (2, 7),
       (3, 5),
       (3, 6),
       (3, 7),
       (4, 8),
       (4, 9),
       (4, 10),
       (4, 11),
       (4, 12),
       (5, 8),
       (5, 9),
       (5, 10),
       (5, 11),
       (5, 12);

INSERT INTO collections (name, release_year)
VALUES ('Old school', 1995),
       ('Metal and beer', 1996),
       ('Abracadabra', 2018),
       ('Gold collection', 2019);

INSERT INTO collections_tracks (collection_id, track_id)
VALUES (1, 6),
       (1, 8),
       (1, 10),
       (1, 16),
       (1, 3),
       (2, 2),
       (2, 9),
       (2, 27),
       (2, 20),
       (2, 14),
       (2, 8),
       (3, 1),
       (3, 28),
       (3, 7),
       (3, 4),
       (3, 6),
       (4, 19),
       (4, 5),
       (4, 11),
       (4, 22),
       (4, 13);